import { PrismaClient, Category } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const items = [
    {
      name: 'Oversized Street T-Shirt',
      type: Category.Tshirt,
      price: 250000,
      rating: 4.5,
      image: 'https://source.unsplash.com/random/400x400?tshirt',
      isHot: true,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      stock: 35,
      description: 'T-Shirt oversized gaya street yang nyaman untuk dipakai harian.',
    },
    {
      name: 'Essential Hoodie Black',
      type: Category.Hoodies,
      price: 450000,
      rating: 4.7,
      image: 'https://source.unsplash.com/random/400x400?hoodie',
      isHot: true,
      isNew: false,
      isFeatured: true,
      isOnSale: true,
      stock: 20,
      description: 'Hoodie hitam klasik dengan bahan fleece lembut.',
    },
    {
      name: 'Luxury Designer Jacket',
      type: Category.luxury,
      price: 2500000,
      rating: 4.9,
      image: 'https://source.unsplash.com/random/400x400?luxury,fashion',
      isHot: false,
      isNew: false,
      isFeatured: true,
      isOnSale: false,
      stock: 5,
      description: 'Jaket mewah untuk tampilan premium dan eksklusif.',
    },
    {
      name: 'Classic Bomber Jacket',
      type: Category.Jackets,
      price: 650000,
      rating: 4.3,
      image: 'https://source.unsplash.com/random/400x400?jacket',
      isHot: false,
      isNew: true,
      isFeatured: false,
      isOnSale: true,
      stock: 12,
      description: 'Bomber jacket klasik untuk gaya kasual sehari-hari.',
    },
    {
      name: 'Urban Streetwear Pants',
      type: Category.Streetwear,
      price: 400000,
      rating: 4.6,
      image: 'https://source.unsplash.com/random/400x400?streetwear',
      isHot: true,
      isNew: false,
      isFeatured: true,
      isOnSale: false,
      stock: 18,
      description: 'Celana streetwear dengan desain urban modern.',
    },
    {
      name: 'Graphic Sweatshirt Oversized',
      type: Category.Sweatshirts,
      price: 350000,
      rating: 4.4,
      image: 'https://source.unsplash.com/random/400x400?sweatshirt',
      isHot: false,
      isNew: true,
      isFeatured: false,
      isOnSale: true,
      stock: 25,
      description: 'Sweatshirt dengan desain grafis keren dan nyaman dipakai.',
    },
    // Tambahan variasi dari tiap kategori
    {
      name: 'Premium White T-Shirt',
      type: Category.Tshirt,
      price: 190000,
      rating: 4.1,
      image: 'https://source.unsplash.com/random/400x400?white+tshirt',
      isHot: false,
      isNew: false,
      isFeatured: false,
      isOnSale: true,
      stock: 40,
      description: 'Kaos putih premium untuk tampilan clean.',
    },
    {
      name: 'Techwear Hoodie',
      type: Category.Hoodies,
      price: 500000,
      rating: 4.8,
      image: 'https://source.unsplash.com/random/400x400?techwear',
      isHot: true,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      stock: 10,
      description: 'Hoodie dengan desain futuristik techwear.',
    },
    {
      name: 'Luxury Fur Coat',
      type: Category.luxury,
      price: 3500000,
      rating: 4.9,
      image: 'https://source.unsplash.com/random/400x400?fur+coat',
      isHot: false,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      stock: 3,
      description: 'Coat berbulu mewah untuk musim dingin.',
    },
    {
      name: 'Denim Jacket Blue',
      type: Category.Jackets,
      price: 550000,
      rating: 4.2,
      image: 'https://source.unsplash.com/random/400x400?denim+jacket',
      isHot: false,
      isNew: false,
      isFeatured: true,
      isOnSale: true,
      stock: 8,
      description: 'Jaket denim klasik warna biru.',
    },
    {
      name: 'Graffiti Sweatshirt',
      type: Category.Sweatshirts,
      price: 380000,
      rating: 4.3,
      image: 'https://source.unsplash.com/random/400x400?graffiti+clothing',
      isHot: false,
      isNew: false,
      isFeatured: false,
      isOnSale: true,
      stock: 17,
      description: 'Sweatshirt dengan motif graffiti kreatif.',
    },
    {
      name: 'Limited Edition Streetwear Tee',
      type: Category.Streetwear,
      price: 450000,
      rating: 4.7,
      image: 'https://source.unsplash.com/random/400x400?limited+streetwear',
      isHot: true,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      stock: 10,
      description: 'T-shirt streetwear edisi terbatas dengan desain eksklusif.',
    },
    {
      name: 'Vintage Graphic Tee',
      type: Category.Tshirt,
      price: 220000,
      rating: 4.0,
      image: 'https://source.unsplash.com/random/400x400?vintage+tshirt',
      isHot: false,
      isNew: true,
      isFeatured: false,
      isOnSale: true,
      stock: 30,
      description: 'T-shirt dengan desain grafis vintage yang unik.',
    },
    {
      name: 'Retro Hoodie',
      type: Category.Hoodies,
      price: 480000,
      rating: 4.6,
      image: 'https://source.unsplash.com/random/400x400?retro+hoodie',
      isHot: true,
      isNew: false,
      isFeatured: true,
      isOnSale: false,
      stock: 15,
      description: 'Hoodie dengan desain retro yang stylish.',
    },
    {
      name: 'Designer Leather Jacket',
      type: Category.luxury,
      price: 3000000,
      rating: 4.8,
      image: 'https://source.unsplash.com/random/400x400?leather+jacket',
      isHot: false,
      isNew: true,
      isFeatured: true,
      isOnSale: false,
      stock: 7,
      description: 'Jaket kulit desainer untuk tampilan mewah.',
    },
    {
      name: 'Casual Windbreaker',
      type: Category.Jackets,
      price: 600000,
      rating: 4.1,
      image: 'https://source.unsplash.com/random/400x400?windbreaker',
      isHot: false,
      isNew: false,
      isFeatured: true,
      isOnSale: true,
      stock: 20,
      description: 'Windbreaker kasual',
    },
    {
      name: 'Minimalist Sweatshirt',
      type: Category.Sweatshirts,
      price: 320000,
      rating: 4.5,
      image: 'https://source.unsplash.com/random/400x400?minimalist+sweatshirt',
      isHot: false,
      isNew: true,
      isFeatured: false,
      isOnSale: true,
      stock: 22,
      description: 'Sweatshirt dengan desain minimalis yang elegan.',
    },
    {
      name: 'Urban Cargo Pants',
      type: Category.Streetwear,
      price: 420000,
      rating: 4.4,
      image: 'https://source.unsplash.com/random/400x400?cargo+pants',
      isHot: true,
      isNew: false,
      isFeatured: true,
      isOnSale: false,
      stock: 18,
      description: 'Celana cargo streetwear dengan banyak kantong.',
    },
    
  ];

  for (const item of items) {
    await prisma.item.create({
      data: {
        ...item,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
  }

  console.log(`✅ Seeded ${items.length} items successfully.`);
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e);
    process.exit(1);
  })
  .finally(() => {
    prisma.$disconnect();
  });




